In [2]:
import numpy as np
a1=[30,40,50]
print(a1)

np.array(a1)


[30, 40, 50]


array([30, 40, 50])

In [ ]:
a2=[10,20,"30"]
np.array(a2)


array(['10', '20', '30'], dtype='<U21')

In [ ]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
y=np.zeros(10,int)
print(y)
y.dtype

[0 0 0 0 0 0 0 0 0 0]


dtype('int64')

In [ ]:
np.zeros((3,4)) #2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a3=np.ones(5)
a3[3]="3"
print(a3)

[1. 1. 1. 3. 1.]


In [ ]:
a4=np.zeros((3,4,5))
print(a4)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
a4=np.zeros((3,4,5))
#a4[0][1][2]
#a4[0][1]
#a4[0]

a4.shape
a4[2:5]


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
a5=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a5)
print(a5[:,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [ ]:
a5=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#a5[1:3,0]
a5[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [1]:
import math as m

In [4]:
x=np.array([1,2,3])
y=np.array([3,5,6])
x=x+10
print(x)
print(x+y)

[11 12 13]
[14 17 19]


In [7]:
print(x*2)
print(x*y)
print(x**3)
print(x.mean())
print(x.sum())

[22 24 26]
[33 60 78]
[1331 1728 2197]
12.0
36


In [8]:
#Euclidean Distance
p1=np.array([2,2,2])
p2=np.array([1,1,1])

distance=np.sqrt(np.sum((p1 - p2) ** 2))
print("Distance:", distance)



Distance: 1.7320508075688772


In [9]:
m1 = np.array([[1, 2],
               [3, 4]])

m2 = np.array([[5, 6],
               [7, 8]])

result = m1.dot(m2)
print(result)


[[19 22]
 [43 50]]


In [11]:
import numpy as np

# Create a 2D NumPy array
a = np.array([[1, 2, 3], [4, 5, 6]])

#size
print("Size (total elements):", a.size)

# shape
print("Shape (rows, cols):", a.shape)

#datatype
print("Data Type of elements:", a.dtype)

# astype
# Convert the array from int to float
b = a.astype(float)
print("Array after converting to float:\n", b)
print("New Data Type:", b.dtype)

#tolist
#Convert NumPy array to Python list
py_list=a.tolist()
print("Converted to Python list:", py_list)

Size (total elements): 6
Shape (rows, cols): (2, 3)
Data Type of elements: int64
Array after converting to float:
 [[1. 2. 3.]
 [4. 5. 6.]]
New Data Type: float64
Converted to Python list: [[1, 2, 3], [4, 5, 6]]


In [12]:
# Original array
a = np.array([1, 2, 3])

# copy
# Creates a deep copy (completely independent)
b = a.copy()
b[0] = 100
print("Original array after copy:", a)
print("Copied array (b):", b)

# view
# Creates a shallow copy (shares data with original)
c = a.view()
c[1] = 200
print("Original array after view modification:", a)
print("Viewed array (c):", c)


Original array after copy: [1 2 3]
Copied array (b): [100   2   3]
Original array after view modification: [  1 200   3]
Viewed array (c): [  1 200   3]


In [13]:
# Original array
a = np.array([3, 1, 4, 1, 5])

# sort
# Using np.sort()
sorted_array = np.sort(a)
print("Sorted array (new):", sorted_array)
print("Original array remains unchanged:", a)

# Using in-place sort – modifies the original array
a.sort()
print("Original array after in-place sort:", a)


Sorted array (new): [1 1 3 4 5]
Original array remains unchanged: [3 1 4 1 5]
Original array after in-place sort: [1 1 3 4 5]
